title: Nescale
description: open-source Scala projects
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: true
  repository_url: https://github.com/nescale
